pranav2012/Python-fest2020

- Operators.py
> New commit

- Classes.py
> New update

- python/BinarySearchRecursive.py
- python/LinearSearch.py
List of contents:
- Linear Search (Beginner)
- Binary Search (Beginner)
> Added Linear and Binary searching algorithms

- python/DNS_Lookup.py
@pranav2012 Please review my PR, and do let me know if any changes required
> Created DNS_Lookup.py

- python/Linked_List.py
Added Linked List implementation in python.
Fix issue : #10
- New Script
> Added Linked_List.py

- python/Face Detection/Needed Packages.txt
- python/Face Detection/face_detection.py
- python/Face Detection/haarcascade_frontalface_default.xml
> Added Face Detection

- python/is_palindrome_possible.py
Please merge my pull request as a part of the HacktoberFest 2020
> Added Program to check whether or not palindrome of the given word are possible

- python/stack.py
> Added stack_implementation #8

- python/reverse.py
Hi, 
This is my first contribution to open source. Please merge this on 1st October.
Thanks.
> Reverse String Program

- python/primeno.py
Prime Number question completed. Code has been written in Python in order to take user input and verify whether it is prime or not
> Python Prime Number Question for Hacktoberfest 2020

- python/factorial.py
- python/max_number.py
This is the pull request for the issues #7 and the factorial issue #2
> max number from a list and Factorial #2 and #7

- python/Checkleapyear.py
Check leap year program by akshay
> Checkleapyear.py

- number-guessing-game.py
this is my first PR pls help me to support open source by adding this PR ASAP. thank you
> number-guessing-game.py

- Factor of Number.py
Added a python program to find Factor of a Number
> Factor of a Number.py

- TicTacToe.py
to play this game run " python TicTacToe.py "
> added Tic-Tac-Toe game.

- python/SquareRoot.py
Square root of a positive integer using Newton Raphson method
> added a python code

- Recursive_Factorial.py
- python/Recursive_Factorial.py
> Recursive Factorial

- bank management/README.MD
- bank management/nitin bank.py
As I can see in this repo, there was no bank management system. So, contributed with the same.  I've attached the README file for a better understanding of the program. It's completely in Python & we can do the following: 
- Check balance 
- Withdraw money
- Pay in
- Return card
as normal functionality of a simple bank.
Please tag this PR under 'hacktober fest 2021'.
> Added a mini project in bank management

- ArInvisibilityCloak.py
I have added an invisibility cloak program to the repository
> Added Invisibility Clock program

- python/Jumping_Number.py
This program checks whether the user given input, N is jumping number or not.
> Added Jumping Number script in Python
